server {
    listen 80;
    server_name dex.pi-hybrid.org;

    location / {
        proxy_pass http://pi-frontend:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

server {
    listen 80;
    server_name api.pi-hybrid.org;

    location /amm/ {
        proxy_pass http://pi-amm:3000/;
    }

    location /orderbook/ {
        proxy_pass http://pi-orderbook:8000/;
    }
}
